### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by HN-ux** [Shoalsteed/UX#11]
**Device details**
Win 10
Chrome browser
VPN (private)

**User details**
-Likes building things:-)
-Has gone through a revolution which inspired digital rights activism

**Where she lives and works**

![image](https://user-images.githubusercontent.com/80400452/116533308-e5bac100-a8e9-11eb-883c-ed14975a101d.png)
"Middle East, SW Asia and NE Africa c1955" by davecito is licensed under CC BY 2.0 

**Community** 

![image](https://user-images.githubusercontent.com/80400452/116533689-59f56480-a8ea-11eb-9260-598fe20fc421.png)

![image](https://user-images.githubusercontent.com/80400452/116533760-6da0cb00-a8ea-11eb-8a78-171b4f1a1b97.png)

**Comment by Shoalsteed** [comment]
User Story:
A small org activist group.

- They are global
- they need to have same communication and file sharing but have not much funding to invest in or maintain infrastructure.
- For email they could use Bote to ensure secure email 
- they can use snark for file sharing
- they can host a private irc or forum as a service for invite only.

In this way I2P can be used as secure communication infra for org that wish to lock down some or all of their work to minimize spam, phishing, or a centralized service being shut down or hacked.

**Comment by Shoalsteed** [comment]
Small static sites to sell art , shirts, stickers using cryptocurrency payments and i2P mail to communicate with buyers.

**Comment by Shoalsteed** [comment]
**A better social media**

- I want to start a small forum where my friends and i can post pics, chat without it being public.
- I do not want to use a platform that encourages gamification or allows people to randomly join
- I want it to be a trusted invite only space where people feel safe and can collaborate and share 
- I want it to not be dependent on a corporation that can shut it down or collect our data or make members use phone numbers to create an account.

A private service on I2P with a non public b32 address that is only shared when a new person is invited to join.

**Comment by Shoalsteed** [comment]
**For Journalists - Scope & Considerations**

Some good points raised here, https://internews.org/blog/charting-the-security-needs-of-central-european-journalists/ highlighting some :

- what are the basics of digital. security? 
- what are high risk or low risk security strategies? 
- Interesting to think about if as the article suggests that some journalists do not consider themselves high risk targets for hackers, etc due to what they cover, but often they are simply due to this reduced security posture. In this case an attacker can gain access to other assets through this target. 
- workflows and organizational security strategies
- _Journalists often work under tight deadlines and rarely have the luxury of time for self-study or to tweak their workflows. As one interviewee explained, “I’m a busy parent, and a journalist. So, I have to choose between cooking and learning about security, and cooking always wins.”_  

_"Digital security guides rarely focus on a single journalistic user journey or workflow (for example, ‘securely contacting a source’ or ‘viewing an untrusted document’), and it sometimes felt like journalists would need to modify their workflows towards digital security priorities, rather than the other way around. Not only this, but existing trainings rarely focused on usability, or overemphasized tools or training techniques at the cost of operational advice. In short, the trainings hardly offered ways in which journalists could easily integrate new security behaviors into their existing day-to-day activities"._
