### ISSUE TITLE
Download Page 

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#18]
For most platforms and systems, getting I2P installed and running will consist of up to three steps.

**1**:  **Install Java**
The I2P software is written in Java and requires that Java be installed to run. In addition to the I2P download, you need to install Java if you do not have it already installed. I2P requires Java Runtime Version 7 or higher. (Oracle, OpenJDK, or IcedTea Java Version 7 or 8 recommended, except Raspberry Pi: OpenJDK 9 for ARM, PowerPC: IBM Java SE 7 or 8)
Determine your installed Java version here or type java -version at your command prompt. 

Only two platforms do not require Java to be installed before I2P is installed, those platforms are:

**Android**: Android comes with a Java virtual machine as part of the platform, which I2P for Android uses. Therefore it is not necessary to install Java to use I2P for Android.
**Debian and Ubuntu**: On Debian and Ubuntu when using a .deb package to install, the system will automatically install and configure a Java environment for you.

**_Windows: Java 8 is recommended. Java 9 or higher may not work._

**2**: **Download and Install I2P**
Once you have Java installed, you can install I2P. This step applies to all systems. If you have forgot to install Java, there will be an error message to remind you to do that. 

**3**: ***Install/Configure a Browser** You will need to configure your preferred browser to access the I2P network so that you can browse the network and make use of the applications that are included in the software. Detailed instructions are available on the Web Browser Configuration page.

Release Notes
Change Log
Debian Change Log
Android Change Log

The I2P software includes all of the introductory applications that you need to connect and start participating in the I2P network and community. These include email, bittorrent, and a basic I2P Site for you to personalize and share. Additionally, you can keep track of your network health and connections easily with the status data in the sidebar of the console. 

For first time installations,  a set up wizard will help you configure a few important things like how much bandwidth you would like to share while your router begins to make connections to the network. After the set up wizard is complete, you will be directed to the console home page where you can access the rest of the applications or configure, monitor, or troubleshoot your I2P connections.

**Comment by luciewho** [comment]
Should the numbered sections be:


**1: Install Java**
The software I2P software is written in Java and requires that Java be installed to run. In addition to the I2P download, you need to install Java if you do not have it already installed. I2P requires Java Runtime Version 7 or higher. (Oracle, OpenJDK, or IcedTea Java Version 7 or 8 recommended, except Raspberry Pi: OpenJDK 9 for ARM, PowerPC: IBM Java SE 7 or 8)
Determine your installed Java version here or type java -version at your command prompt.

Only two platforms do not require Java to be installed before I2P is installed, those platforms are:

- Android*: Android comes with a Java virtual machine as part of the platform, which I2P for Android uses. Therefore it is not necessary to install Java to use I2P for Android.
- Debian and Ubuntu: On Debian and Ubuntu when using a .deb package to install, the system will automatically install and configure a Java environment for you.

**Windows: Java 8 is recommended. Java 9 or higher may not work.

**2: Download and Install I2P**
Once you have Java installed, you can install I2P. This step applies to all systems. If you have forgot to install Java, there will be an error message to remind you to do that.

**3: Install/Configure a Browser** 
You will need to configure your preferred browser to access the I2P network so that you can browse the network and make use of the applications that are included in the software. Detailed instructions are available on the Web Browser Configuration page.



![](https://user-images.githubusercontent.com/50714166/112362101-762e3200-8caa-11eb-9dcd-5f93589886ce.png)
From issue #9

**Comment by Shoalsteed** [comment]
add the 'whats this " to sigs and mirrors.

**Comment by Shoalsteed** [comment]
Add DOWNLOAD to buttons
add links from mirrors and sigs to a page to give an explanation that includes exact instructions on how to use GPG and sha256sum to verify the signatures ( IDK)
