### ISSUE TITLE
Sidebar Troubleshooting Messages

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#29]
![Screen Shot 2021-08-26 at 11 54 06 AM](https://user-images.githubusercontent.com/50714166/130999515-d2ad0d11-bc6c-4b9c-977d-5f181ab12183.png)

**Comment by Shoalsteed** [comment]
![Screen Shot 2021-08-26 at 11 54 15 AM](https://user-images.githubusercontent.com/50714166/130999544-b5a165cb-6aee-4a7e-8cf8-c59e90a79d96.png)

**Comment by eyedeekay** [comment]
> ![Screen Shot 2021-08-26 at 11 54 06 AM](https://user-images.githubusercontent.com/50714166/130999515-d2ad0d11-bc6c-4b9c-977d-5f181ab12183.png)

This is temporary and there's not much the user can do about it. It is not something to worry about most of the time. It will go away after a little while.

**Comment by eyedeekay** [comment]
> ![Screen Shot 2021-08-26 at 11 54 15 AM](https://user-images.githubusercontent.com/50714166/130999544-b5a165cb-6aee-4a7e-8cf8-c59e90a79d96.png)

Different for every platform and every SOHO modem/router/IGD. It will also be different for every single VPN provider so none of the instructions will work for VPN users. But, the broad steps of this process will be:

1. Find the external port used by your I2P router
2. Examine the local Firewall to make sure that the port is open
3. Determine the necessary information about your default gateway in order to log in
4. Log into your default gateway and either:
5. Enable UPnP **or**
6. Set up a static route and forward the router port to your routers local address.
