### ISSUE TITLE
Timeline and Deliverables

### ISSUE THREAD

**Issue by luciewho** [Shoalsteed/UX#40]
Creating a space to put some of our goals/milestones and a rough timeline of when we'd like to hit each one.

**Comment by Shoalsteed** [comment]
### Landing Page
-refine copy and calls to action.
-decide where all links will go and decide if any modifications need to be made in deeper IA layers.
-Decide on palette and graphic assets. Add to Style Guide.
-Test wireframe

### New Users and Contributor Docs
-improve tone and language and engagement
-clean up ( ie remove reference to Monotone, prioritize the best and most accessible way to do things.
-get rid of redundancy 

### Dev & Tech Docs
-ensure that every page on the site is accounted for in the wireframe ( not copied, but at least referenced since there are hundreds of pages on the site.

### Usability Research
-test our work
-talk to more journalists about threat models and concerns and tools they use in order to do a needs pairing with what I2P offers.

### Style Guide
Complete the Style Guide and add to Git and site.

**Comment by luciewho** [comment]
[Timeline.xlsx](https://github.com/Shoalsteed/UX/files/7316677/Timeline.xlsx)

I made this in Mac Numbers so hopefully the Excel export works on here (Numbers can't be uploaded on Github). 
Sheet 1 is the Timeline. Sheet 2 is for Development which will need input from idk.

**Comment by luciewho** [comment]
Now on Google Sheets! https://docs.google.com/spreadsheets/d/1lsCwC62KGcE_HEwOCko1Rt-oMGmwiWwU/edit?usp=sharing&ouid=110028671902304356519&rtpof=true&sd=true
