### ISSUE TITLE
Browser Configuration ( Outproxy TOS Update)

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#55]
THE PRIVACY SOLUTIONS SITE IS NOT ACTIVE ANY LONGER. I have updated the copy below:

Outproxy 

I2P is not designed for creating proxies to the Internet. 
Tor provides a browser to use as an outproxy to the Internet.

The I2P Project does not run any proxies to the Internet.
The  I2P software includes two outproxies: false.i2p and outproxy-tor.meeh.i2p. Even the domain names are different, it's the same outproxy you hit. (multi-homed/keyed for better performance). These are run by a volunteer.

Filtering is active on these outproxies (for example, mibbit and torrent tracker access is blocked). I2P Sites that are accessible via .i2p addresses are also not allowed via the outproxies. As a convenience, the outproxy blocks ad servers.

**Comment by Shoalsteed** [comment]
For the browser options:

Does it make sense to only suggest Firefox?
 If it is truly the best option to work with I2P , why should we include other options, especially if they create privacy concerns?
It also means that the screenshots and instructions need to always be kept up to date ideally.

**Comment by eyedeekay** [comment]
I don't have a good way to answer this one. I'm committedly anti-monoculture, but I also really, really don't think Chromium can provide a reasonable basis for a private browser without someone spending the bulk of their time to modifying Chromium in such a way that it provides a reasonable basis for a private browser. The problems are that there is a great deal of built-in telemetry, it is difficult to determine how fingerprintable they are, they have inconsistently-supported settings, and that they are designed to communicate more information about the user's activity to servers and between sites, rather than less. It's not impossible, but it's not a good situation.

**Comment by Shoalsteed** [comment]
I guess that if the project would not suggest using Chrome as part of a proper privacy workflow with the I2P network, I would suggest that if Chrome could create an issue for a user, we should not present it as an option. 

My argument is about equipping a user with the best option available as a practical purpose.

**Comment by eyedeekay** [comment]
It's also sort of a "Private from Who" situation. For one thing, (vendor A)'s browser will generally not include (vendor B)'s telemetry. But if you trust (vendor A) or (vendor B) already then maybe you don't care. I assume that this is the reason people use Microsoft Edge. But if I'm not a vendor, and I'm just serving you a site, I'm going to have an easier time profiling consistently you if you are using Chromium than if you are using Firefox. But if I'm not trying actively to profile you, then maybe it's more important for you to just have a browser than for it to be the "Best" browser.

**Comment by eyedeekay** [comment]
There's also the "Our browser landscape is already horribly fragmented, do we try to help existing Chromium users because we don't think they're going away/going to switch to Firefox" thing to consider. I really do not know the answer to all these questions, in fact I don't think that the people acting on the answers to these questions(Iceweasel, Brave) know the answers.
