### ISSUE TITLE
Reseed Tools

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#56]
https://reseed.i2pgit.org/

**You have found an I2P Reseed**
_Maybe it was by accident, or maybe you visited the URL because you saw it in the software somewhere. While we’ve got your attention, we’re going to take this opportunity to tell you a little about what we do here. I2P is a peer-to-peer network which uses “Garlic Routing” to maintain privacy. Reseed nodes help you get connected to I2P for the first time, and even though you should only have to use them once in a great while, they are very important services._

How would anyone find tis page? Where is it listed?
If this is the UI for the plugin? If so what is it meant to do? 
Are there 2 clear reasons to end up on this page or one? What do we want to achieve?

**Comment by Shoalsteed** [comment]
If linking to website, use this as an opportunity to build trust.
maybe state that this site / plugin is maintained by the I2P Core team?

**Comment by Shoalsteed** [comment]
_Here on purpose? Here’s a one-time link to a reseed bundle for you._

How would a person end up here on purpose?
Is there a way to create trust with the bundle ie a signature?

**Comment by Shoalsteed** [comment]
![1](https://user-images.githubusercontent.com/50714166/144895708-dd94b777-e8dc-4baa-bfab-1fa73f873f6c.png)
![2](https://user-images.githubusercontent.com/50714166/144895709-49f97a51-b689-4668-9cfb-b165b3835877.png)
![3](https://user-images.githubusercontent.com/50714166/144895710-3ee3a306-4412-48f9-89a4-ef608731de01.png)

**Comment by Shoalsteed** [comment]
above are three options for a new welcome image on the webpage

**Comment by eyedeekay** [comment]
> https://reseed.i2pgit.org/
> 
> **You have found an I2P Reseed** _Maybe it was by accident, or maybe you visited the URL because you saw it in the software somewhere. While we’ve got your attention, we’re going to take this opportunity to tell you a little about what we do here. I2P is a peer-to-peer network which uses “Garlic Routing” to maintain privacy. Reseed nodes help you get connected to I2P for the first time, and even though you should only have to use them once in a great while, they are very important services._
> 
> How would anyone find tis page?

Lots of ways, in particular search engines might crawl it after analyzing our source code or looking up DNS-related information about our web sites.

> Where is it listed?

In the source code and in the router console on http://127.0.0.1:7657/configreseed

> If this is the UI for the plugin? 

Yes

> If so what is it meant to do?

Distract browser users, capture search crawlers, and keep everything that isn't an I2P router from getting the reseed file itself. and redirect them to the website.

> Are there 2 clear reasons to end up on this page or one?

Every reason that isn't a reason to download the reseed itself is a reason to land on this page instead. That includes:

 - Being a search crawler. It would be tantamount to scraping for a search engine to harvest I2P reseed files. This turns a negative into a positive by making it unlikely that a crawler would manage to download the reseed successfully, and instead proffering a link back to the project page.
 - Being a web browser operated by an end-user. Being anything but an I2P router. There is almost never a reason to download a reseed file with a browser. This turns a negative into a positive by exposing something that encourages users to visit the I2P Project site to learn more, instead of what some of proffering a reseed file directly or what some of the old reseed servers used to do(Remember "Nothing here, F Off?").

> What do we want to achieve?

Distract browser users, capture search crawlers, and keep everything that isn't an I2P router from the reseed file itself. and redirect them to the website.

**Comment by eyedeekay** [comment]
> _Here on purpose? Here’s a one-time link to a reseed bundle for you._
> 
> How would a person end up here on purpose?
Anything from:
 - They would be offered a reseed URL by someone operating that reseed server, probably on a private basis for a small group of people, perhaps they would host it via an onion.
 - They would copy-and-paste one of the URL's from http://127.0.0.1:7657/configreseed just to see what happens.

> Is there a way to create trust with the bundle ie a signature?

Yes, this server only gives out signed reseed bundles

**Comment by eyedeekay** [comment]
> ```![1](https://user-images.githubusercontent.com/50714166/144895708-dd94b777-e8dc-4baa-bfab-1fa73f873f6c.png) ![2](https://user-images.githubusercontent.com/50714166/144895709-49f97a51-b689-4668-9cfb-b165b3835877.png) ![3](https://user-images.githubusercontent.com/50714166/144895710-3ee3a306-4412-48f9-89a4-ef608731de01.png)```

I like the top and the bottom ones, preference is for the one on top

**Comment by Shoalsteed** [comment]
> > `![1](https://user-images.githubusercontent.com/50714166/144895708-dd94b777-e8dc-4baa-bfab-1fa73f873f6c.png) ![2](https://user-images.githubusercontent.com/50714166/144895709-49f97a51-b689-4668-9cfb-b165b3835877.png) ![3](https://user-images.githubusercontent.com/50714166/144895710-3ee3a306-4412-48f9-89a4-ef608731de01.png)`
> 
> I like the top and the bottom ones, preference is for the one on top

The garlic is the one I would go with as well

**Comment by Shoalsteed** [comment]
What will the icon that you mentioned  be used for?
How many UI elements are required?

**Comment by Shoalsteed** [comment]
> > https://reseed.i2pgit.org/
> > **You have found an I2P Reseed** _Maybe it was by accident, or maybe you visited the URL because you saw it in the software somewhere. While we’ve got your attention, we’re going to take this opportunity to tell you a little about what we do here. I2P is a peer-to-peer network which uses “Garlic Routing” to maintain privacy. Reseed nodes help you get connected to I2P for the first time, and even though you should only have to use them once in a great while, they are very important services._
> > How would anyone find tis page?
> 
> Lots of ways, in particular search engines might crawl it after analyzing our source code or looking up DNS-related information about our web sites.
> 
> > Where is it listed?
> 
> In the source code and in the router console on http://127.0.0.1:7657/configreseed
> 
> > If this is the UI for the plugin?
> 
> Yes
> 
> > If so what is it meant to do?
> 
> Distract browser users, capture search crawlers, and keep everything that isn't an I2P router from getting the reseed file itself. and redirect them to the website.
> 
> > Are there 2 clear reasons to end up on this page or one?
> 
> Every reason that isn't a reason to download the reseed itself is a reason to land on this page instead. That includes:
> 
> * Being a search crawler. It would be tantamount to scraping for a search engine to harvest I2P reseed files. This turns a negative into a positive by making it unlikely that a crawler would manage to download the reseed successfully, and instead proffering a link back to the project page.
> * Being a web browser operated by an end-user. Being anything but an I2P router. There is almost never a reason to download a reseed file with a browser. This turns a negative into a positive by exposing something that encourages users to visit the I2P Project site to learn more, instead of what some of proffering a reseed file directly or what some of the old reseed servers used to do(Remember "Nothing here, F Off?").
> 
> > What do we want to achieve?
> 
> Distract browser users, capture search crawlers, and keep everything that isn't an I2P router from the reseed file itself. and redirect them to the website.

So, the "site" is not a UI, it is more of a decoy that assumes that things are looking for reseeds? It is not a site for the plugin?

**Comment by eyedeekay** [comment]
It is exactly a site for the plugin and the only type of UI it can have. So is the reseed bundle itself. They are both a web site, because all a reseed is is a web site with a reseed bundle on it. The plugin is a web site is a reseed. The difference is that when used correctly, the feedback from reseeding occurs only in the user's I2P router, "Reseeded successfully" because that is A) all that needs to happen and B) The only possible place to expose that feedback. For the purposes of the reseed process in most I2P routers, what you are looking at when you visit https://reseed.i2pgit.org in a browser is an **error page**, if you're seeing it in a browser then it's probably not what you want. If you're not an I2P router then there's an extremely high chance you're on the wrong page. The only case where you are not on the wrong page is if you're trying to download the reseed bundle using the one-time link at the bottom of the page, which is the `"They would be offered a reseed URL by someone operating that reseed server, probably on a private basis for a small group of people, perhaps they would host it via an onion."` case.

**Comment by eyedeekay** [comment]
> What will the icon that you mentioned be used for? 

It will appear in the router console homepage when the reseed plugin is successfully running. Functionally, it is a link to the reseed server's homepage.

> How many UI elements are required?

There are three paths a user can take on this page

1. direct user to geti2p.net if they click a link
2. provide a one-time link to a reseed bundle in case they're there on purpose
3. close the page

Those are all of the tasks. The existing elements cover those tasks but don't look good.

**Comment by Shoalsteed** [comment]
Revised copy:

_You have found an I2P Reseed_

I2P is a peer-to-peer network which uses “Garlic Routing” to maintain privacy. Reseed nodes help you get connected to I2P for the first time, and even though you should only have to use them once in a great while, they are very important services.

To learn more about the purpose of reseeds, visit the I2P Project website:

Learn more about reseeds here:
Learn how to run a reseed here:
Read the reseed server code and learn about more reseed options here:

Having connection issues?  Here is a one-time link to a reseed bundle for you.

Reseed

**Comment by Shoalsteed** [comment]
The entire page is finicky because if you click anywhere on it by accident it links to the I2P site.

Font should be changed.

Make button round.

**Comment by Shoalsteed** [comment]
Background #D9D9D9
Font: Roboto
Text: Black

![this is an i2p reseed server ](https://user-images.githubusercontent.com/50714166/145039192-d4434066-e7d8-4a16-9546-3331e1673d30.png)

**Comment by Shoalsteed** [comment]
@eyedeekay before I close this, I would suggest using the poster on the repo that people visit.

**Comment by eyedeekay** [comment]
Done
