### ISSUE TITLE
Blizzard

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#57]
**Blizzard: The I2P Snowflake donor Plugin** 

This is standalone version of the Tor Project's "Snowflake" proxy, which can be used to produce an I2P Plugin that will donate a Snowflake to Tor Browser Users. The Snowflake uses I2P to manage it's life-cycle. That means when you start and stop your I2P router, you start and stop the snowflake.

**Blizzard is Privacy Mutual Aid**

We are developing a generation of privacy-aware applications motivated by mutual aid, meant to  increase the strengths of other applications in the Privacy and Peer-to-Peer ecosystem.

We learned about instances of attacking Snowflake users by identifying Snowflakes and cutting the users off. This is similar to blocking attempts to I2P where I2P nodes are enumerated and then users are disconnected from those nodes.However, due to I2P's high churn rate, this blocking technique does not appear to have any practical effect on an I2P user's ability to join the network or access information. Blizzard uses I2P's peer diversity, network churn, and obfuscated transport to allow access to Tor in blocked areas and still retain Tor's security properties, and in particular their Exit Diversity. By using a bridge rather than an outproxy as a path to Tor, and accessing that bridge over I2P, we provide greater resistance too blocking.

If you can safely use I2P in non-hidden mode, you're probably able to safely donate a Snowflake long-term. 

**What Does Hidden Mode Mean for the I2P Network?**

When an I2P router is placed in hidden mode, its connection and interaction with the network change in three ways:

It will no longer publish a routerInfo to the NetDB.
It will no longer accept participating tunnels.
It will reject direct connections to routers in the same country that it is in.
These defences make these routers more difficult to enumerate reliably, and prevent them from potentially being in violation of restrictions on routing traffic for others.

The Invisible Internet Project ( I2P Java) takes direction from  civil and digital rights organizations in order to make decisions that offer protections for its users. In this case, the ongoing research provided by Freedom House has been referenced. General guidance is to include countries with a Civil Liberties (CL) score of 16 or less or an Internet Freedom score of 39 or less (not free) on a Strict Countries List and automatically be placed into "Hidden" mode.

To see the countries currently included in this list visit: https://geti2p.net/en/about/restrictive-countries

**Create a Blizzard**

Blizzard For Windows (I2P network link)
Blizzard For Linux (I2P Network Link)

Blizzard For Windows 
Blizzard For Linux 

**About Tor Project's Snowflake:**
Homepage https://snowflake.torproject.org/
Firefox Extension
Chrome Extension
Use the Snowflake Go library to add a proxy to your application

**Comment by Shoalsteed** [comment]
[I2PxTor.pdf](https://github.com/Shoalsteed/UX/files/7669338/I2PxTor.pdf)

**Comment by Shoalsteed** [comment]
![blizzard](https://user-images.githubusercontent.com/50714166/145063774-d66f3f95-a66d-490e-8715-3654cb3edf6f.png)

**Comment by Shoalsteed** [comment]
![I2PxTor (1)](https://user-images.githubusercontent.com/50714166/145066583-9dacb062-b161-40d4-920c-a743667ef7dc.png)
![I2PxTor](https://user-images.githubusercontent.com/50714166/145066592-f52e3b43-79e9-44c7-971a-6724e153becc.png)

**Comment by Shoalsteed** [comment]
Background #545454
Title Font: Farro
Body font open sans
Font colour: #D9D9D9
I2P button #363A68
Clearnet Button #FEFAF0
![3](https://user-images.githubusercontent.com/50714166/145070394-e7b8cf6a-411d-4d55-b1c9-1cf4c065370b.png)
![4](https://user-images.githubusercontent.com/50714166/145070412-e09239a7-18e7-4310-a72a-de671887f160.png)
![snowflake graphic](https://user-images.githubusercontent.com/50714166/145070537-1e748f2e-33cf-4ba7-a5ba-1d015544c880.png)

**Comment by eyedeekay** [comment]
Re: the copy, you've conflated the SAM-PT and the Snowflake Donor. They are related, but not the same thing. SAM-PT is an obfuscated Tor bridge that introduces a single I2P Hop and sets up the connection over SAM to prevent a bridge user or the network itself from being able to see important meta-information about the bridge while it is in use. SAM-PT uses our transports to reach Tor bridges. *This* plugin isn't released yet, because I have a bunch of Linux security stuff(AppArmor, SELinux) stuff I have to figure out before I can effectively package it. Also, the goal I ultimately have with these plugins collectively is to provide capacity back as we use it, therefore it makes sense to deploy Snowflakes(Which only donate capacity) before SAM-PT bridges(Which both donate and use capacity).

Snowflake does a very similar thing on some levels, but it does it via a network of volunteers running proxies that are mostly in their browsers or, in our case, provided by plugins in other applications. Our Snowflake plugin uses the same transports as Tor's and is in fact based on the same code as theirs, and works directly with the rest of their Snowflake system, no I2P involved except where I2P controls the runtime of the Snowflake proxy plugin.

**Comment by eyedeekay** [comment]
I've made revisions to the copy but it's all checked in. Lots of CSS work to do.

**Comment by Shoalsteed** [comment]
Okay, I was wondering if I had that correct. Thanks for clarifying.

**Comment by Shoalsteed** [comment]
> I've made revisions to the copy but it's all checked in. Lots of CSS work to do.

Is the CSS work just for the page itself or are there other elements required?

**Comment by eyedeekay** [comment]
Page itself, right now it just looks like the rest of my website. The website itself is actually embedded in the plugin too, but it's not on by default.

**Comment by Shoalsteed** [comment]
I want to test the readability if the font colour on the background before implementation. It make require an adjustment.
